import { ProductInterface } from "../types/productInter";

export const mockProducts: ProductInterface[] = [
  {
    id: "1",
    name: "Product name 1 and some words to test the length of the name",
    price: 246.75,
    regularPrice: 329,
    smallestPrice: 329,
    rating: 5,
    image: "/images/product1.jpg",
    category: "bestseller",
    sales: 150,
    grams:20,
    tags: ["Promocja", "Nowość"],
    quantity: 100,
  },
  {
    id: "2", 
    name: "Product 2",
    price: 146.25,
    regularPrice: 195,
    smallestPrice: 195,
    rating: 5,
    image: "/images/product2.jpg",
    category: "bestseller", 
    sales: 120,
    grams: 30,
    tags: ["Promocja", "Nowość"],
    quantity: 0,
  },
  {
    id: "3",
    name: "Product 3", 
    price: 156.75,
    regularPrice: 209,
    smallestPrice: 209,
    rating: 5,
    image: "/images/product3.jpg",
    category: "bestseller",
    sales: 100,
    grams: 30,
    tags: ["Promocja"],
    quantity: 100,
  },
  {
    id: "4",
    name: "Laptop XYZ",
    price: 2500,
    regularPrice: 329,
    smallestPrice: 329,
    rating: 5,
    image: "/images/product4.jpg",
    category: "bestseller",
    sales: 80,
    grams:20,
    tags: ["Nowość"],
    quantity: 100,
  },
  {
    id: "5", 
    name: "Smartphone ABC",
    price: 1800,
    regularPrice: 329,
    smallestPrice: 329,
    rating: 5,
    image: "/images/product1.jpg",
    category: "bestseller",
    sales: 95,
    grams:20,
    tags: [],
    quantity: 100,
  }
];
    